server:
  host: localhost
  port: 4000
  log_level: debug
  log_handler: text
  environment: dev
  async_events: True
  input_queue_capacity: 100
  idle_timeout: 30s
  initial_state: debug
  starting_room: limbo:the_void
data:
  accounts_path: _data/accounts
  areas_path: _data/areas
  players_path: _data/players
  characters_path: _data/characters
  users_path: _data/users
  manifest_file: manifest.yml
  rooms_file: rooms.yml
  items_file: items.yml
  mobs_file: mobs.yml