server:
  host: localhost
  port: 4000
  log_level: debug
  log_handler: text
  environment: dev
  async_events: True
  input_queue_capacity: 100
  idle_timeout: 30s
  initial_state: welcome
  starting_room: the_void
  login_enabled: True
  registration_enabled: True
  max_players: 100
  max_input_length: 1024
  password_min_length: 5
  password_max_length: 64
  username_min_length: 3
  username_max_length: 32
  charactername_min_length: 3
  charactername_max_length: 32
  tick_duration: 1000ms
data:
  accounts_path: _data/accounts
  areas_path: _data/areas
  players_path: _data/players
  characters_path: _data/characters
  users_path: _data/users
  manifest_file: manifest.yml
  rooms_file: rooms.yml
  items_file: items.yml
  mobs_file: mobs.yml
banned_names:
  - admin
  - administrator
  - god
  - immortal
  - wizard